In [4]:
!pip install torch

In [5]:
import torch


#1. Creating and Inspecting Tensors:

Exercise: Create a 3x4 tensor filled with random numbers between 0 and 1. Print the tensor's shape, data type, and number of dimensions.


In [6]:
t1 = torch.rand(3,4)
print(t1.shape)
print(t1.dtype)
print(t1.ndim)

torch.Size([3, 4])
torch.float32
2


#2. Tensor Arithmetic:

Exercise: Create two tensors, tensor1 (2x3) and tensor2 (2x3), with random integer values. Perform element-wise addition, subtraction, multiplication, and division.


In [7]:
t2 = torch.rand(2,3)
t3 = torch.rand(2,3)

t4 = t2+t3
t5 = t2-t3
t6 = t2*t3
t7 = t2/t3

print(t2)
print(t3)
print(t4)
print(t5)
print(t6)
print(t7)

tensor([[0.8108, 0.5370, 0.1825],
        [0.8704, 0.5078, 0.9609]])
tensor([[0.9230, 0.4767, 0.7330],
        [0.0879, 0.4429, 0.5567]])
tensor([[1.7338, 1.0137, 0.9154],
        [0.9583, 0.9507, 1.5176]])
tensor([[-0.1123,  0.0604, -0.5505],
        [ 0.7825,  0.0649,  0.4042]])
tensor([[0.7484, 0.2560, 0.1337],
        [0.0765, 0.2249, 0.5349]])
tensor([[0.8784, 1.1267, 0.2490],
        [9.9018, 1.1464, 1.7261]])


# 3. Reshaping Tensors:

Exercise: Create a tensor with values from 1 to 12. Reshape it into a 2x6 tensor and then into a 3x4 tensor.


In [8]:
t8 = torch.arange(1,13)
print(t8)
print(t8.reshape(2,6))
print(t8.reshape(3,4).reshape(1,12))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


# 4. Indexing and Slicing:

Exercise: Create a 5x5 tensor. Extract the following:
- The first row.
- The last column.
- A 3x3 sub-tensor from the center.


In [9]:
t9 = torch.rand(5,5)
print(t9)

print(t9[0,:])
print(t9[:,-1])
print(t9[1:4,1:4])


tensor([[0.6396, 0.7929, 0.1601, 0.7454, 0.9643],
        [0.5865, 0.0389, 0.9075, 0.6910, 0.8403],
        [0.3537, 0.7433, 0.9129, 0.8939, 0.8104],
        [0.9563, 0.5130, 0.7822, 0.3534, 0.6244],
        [0.7806, 0.6704, 0.9532, 0.9882, 0.3402]])
tensor([0.6396, 0.7929, 0.1601, 0.7454, 0.9643])
tensor([0.9643, 0.8403, 0.8104, 0.6244, 0.3402])
tensor([[0.0389, 0.9075, 0.6910],
        [0.7433, 0.9129, 0.8939],
        [0.5130, 0.7822, 0.3534]])


# 5. Tensor Operations (Mean, Sum, Max, Min):

Exercise: Create a 4x4 tensor with random floating-point numbers. Calculate the mean, sum, maximum, and minimum values of the entire tensor and along each row and column.


In [10]:
t10 = torch.rand(4,4)
print(t10)
print(t10.mean(), t10.sum(), t10.max(), t10.min())
print(t10.mean(dim=0, keepdim=True), t10.sum(dim=0), t10.max(dim=0), t10.min(dim=0))
print(t10.mean(dim=1,keepdim=True), t10.sum(dim=1), t10.max(dim=1), t10.min(dim=1))

tensor([[0.9386, 0.4810, 0.6171, 0.5383],
        [0.9651, 0.0387, 0.6567, 0.1572],
        [0.0098, 0.8267, 0.9518, 0.2737],
        [0.5252, 0.5558, 0.7522, 0.0610]])
tensor(0.5218) tensor(8.3490) tensor(0.9651) tensor(0.0098)
tensor([[0.6097, 0.4756, 0.7445, 0.2575]]) tensor([2.4388, 1.9022, 2.9778, 1.0302]) torch.return_types.max(
values=tensor([0.9651, 0.8267, 0.9518, 0.5383]),
indices=tensor([1, 2, 2, 0])) torch.return_types.min(
values=tensor([0.0098, 0.0387, 0.6171, 0.0610]),
indices=tensor([2, 1, 0, 3]))
tensor([[0.6438],
        [0.4544],
        [0.5155],
        [0.4736]]) tensor([2.5751, 1.8176, 2.0621, 1.8943]) torch.return_types.max(
values=tensor([0.9386, 0.9651, 0.9518, 0.7522]),
indices=tensor([0, 0, 2, 2])) torch.return_types.min(
values=tensor([0.4810, 0.0387, 0.0098, 0.0610]),
indices=tensor([1, 1, 0, 3]))


# 6. Tensor Concatenation and Stacking:

Exercise: Create two tensors, tensorA (3x2) and tensorB (3x2). Concatenate them horizontally and vertically. Then, stack them to create a new tensor with an extra dimension.


In [11]:
tensorA = torch.ones(3,2)
tensorB = torch.zeros(3,2)

print(torch.cat((tensorA, tensorB), dim=0))
print(torch.cat((tensorA, tensorB), dim=1))
print(torch.stack((tensorA, tensorB), dim=0))
print(torch.stack((tensorA, tensorB), dim=1))
print(torch.stack((tensorA, tensorB), dim=2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.]])
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
tensor([[[1., 1.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]]])
tensor([[[1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.]]])


# 7. Tensor Element-wise Functions:

Exercise: Create a tensor with random values. Apply the following element-wise functions:
Square root.
Exponential.
Logarithm (handle potential zero values).


In [12]:
t11 = torch.randn(3,2)

print(t11)
print(torch.sqrt(t11.abs()))
print(torch.exp(t11))
print(torch.log(t11.abs() + 1e-6))

tensor([[-0.4617, -1.0000],
        [-0.3669,  1.2459],
        [-1.4756, -0.0345]])
tensor([[0.6795, 1.0000],
        [0.6058, 1.1162],
        [1.2148, 0.1857]])
tensor([[0.6302, 0.3679],
        [0.6928, 3.4762],
        [0.2286, 0.9661]])
tensor([[-7.7288e-01, -4.5122e-05],
        [-1.0025e+00,  2.1990e-01],
        [ 3.8908e-01, -3.3677e+00]])


# 8. Broadcasting:

Exercise: Create a tensor tensor1 (4x3) and a tensor tensor2 (1x3). Add tensor2 to tensor1 using broadcasting.


In [15]:
tensor1 = torch.randn(4,3)
tensor2 = torch.randn(1,3)

print(tensor1)
print(tensor2)
print(tensor1 * tensor2)

tensor([[-0.7045,  1.0054, -0.1072],
        [ 0.8412, -0.6533, -0.8509],
        [ 0.0936, -0.2740,  0.2283],
        [ 0.1660, -0.3945, -2.4175]])
tensor([[0.2175, 0.7945, 0.2764]])
tensor([[-0.1533,  0.7987, -0.0296],
        [ 0.1830, -0.5190, -0.2351],
        [ 0.0204, -0.2177,  0.0631],
        [ 0.0361, -0.3134, -0.6681]])


# 9. Matrix Multiplication:

Exercise: Create two tensors, matrixA (3x4) and matrixB (4x2). Perform matrix multiplication.


In [16]:
matrixA = torch.randn(3,4)
matrixB = torch.randn(4,2)

print(matrixA)
print(matrixB)
print(torch.matmul(matrixA, matrixB))

tensor([[-1.4779,  0.0667, -1.3074,  0.0763],
        [ 1.0411, -0.4321, -0.4063, -0.5638],
        [-0.7029, -0.0195, -1.1644,  0.6317]])
tensor([[-0.8047, -1.9764],
        [ 0.0327,  0.9788],
        [-0.5125,  0.1242],
        [-1.2803, -0.9414]])
tensor([[ 1.7638,  2.7519],
        [ 0.0781, -2.0004],
        [ 0.3530,  0.6308]])


# 10. Moving Tensors to GPU (if available):

Exercise: Create a tensor. Check if a GPU is available. If so, move the tensor to the GPU and perform a simple operation.


In [22]:
t= torch.randn(6,6)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

print(device)

t.to(device)
t = t @ t
t.to("cpu")

cpu


tensor([[ 8.1868, -1.2659, -1.1481,  6.2833, -1.3808, -0.0877],
        [ 0.1051,  2.0825, -2.0111,  2.2905, -0.5134,  0.3203],
        [-0.7450, -0.9693,  2.8140, -3.6114,  0.1160, -0.2192],
        [ 2.6072, -1.7601,  0.1642,  1.6606,  1.2919,  2.1640],
        [ 2.6833,  0.9197, -1.1067,  2.9091,  0.4016,  2.1208],
        [-0.0089,  0.2350, -0.5641,  0.0665,  1.4480,  2.8761]])